import Main from "./Main";
import Login from "./Login";
import Signup from "./Signup";
import CartList from "./CartList";
import CommentWrite from "./CommentWrite";
import NotFound from "./NotFound";
import Detail from "./Detail";
import FindPwd from "./FindPwd";
import FindId from "./FindId";
import Payment from "./Payment";
import OrderList from "./OrderList";
import NoticeListPage from "./NoticeListPage";
import NoticeDetailPage from "./NoticeDetailPage";
import FaqPage from "./FaqPage";
import InquiryPage from "./InquiryPage";
import InquiryFormPage from "./InquiryFormPage";
import Category from "./Category";
import Order from "./Order";
import Address from "./Address";
import ConfirmPwd from "./ConfirmPwd";

export { Main, Login, Signup, CartList, CommentWrite, Detail, NotFound, Category, FindPwd, FindId, Order, Address, NoticeListPage, NoticeDetailPage, FaqPage, InquiryPage, InquiryFormPage, Payment, OrderList, ConfirmPwd };
